/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import Model.DAO.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Day
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTlogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBEntrar = new javax.swing.JButton();
        JBSair = new javax.swing.JButton();
        JPSenha = new javax.swing.JPasswordField();
        jTelaInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTlogin.setToolTipText("");
        JTlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTloginActionPerformed(evt);
            }
        });
        jPanel1.add(JTlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 210, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Senha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        JBEntrar.setBackground(new java.awt.Color(242, 109, 135));
        JBEntrar.setForeground(new java.awt.Color(255, 51, 255));
        JBEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Prancheta 4.png"))); // NOI18N
        JBEntrar.setBorder(null);
        JBEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBEntrar.setFocusCycleRoot(true);
        JBEntrar.setFocusPainted(false);
        JBEntrar.setIconTextGap(1);
        JBEntrar.setVerifyInputWhenFocusTarget(false);
        JBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(JBEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 60, 50));

        JBSair.setBackground(new java.awt.Color(242, 109, 135));
        JBSair.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        JBSair.setForeground(new java.awt.Color(255, 255, 255));
        JBSair.setText("Sair");
        JBSair.setBorder(null);
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });
        jPanel1.add(JBSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 130, 40));

        JPSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(JPSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 210, 40));

        jTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela login.png"))); // NOI18N
        jPanel1.add(jTelaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTloginActionPerformed

    private void JBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEntrarActionPerformed
        // Quando cliclar no botao da ceta:
        this.controller.entrarNoSistema();
        
       
    }//GEN-LAST:event_JBEntrarActionPerformed

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        
        int opcao =JOptionPane.showConfirmDialog(null,"Deseja realmente sair?","Atenção",JOptionPane.YES_OPTION);
        
            if (opcao == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        
    }//GEN-LAST:event_JBSairActionPerformed

    private void JPSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEntrar;
    private javax.swing.JButton JBSair;
    private javax.swing.JPasswordField JPSenha;
    private javax.swing.JTextField JTlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTelaInicial;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null,mensagem); //To change body of generated methods, choose Tools | Templates.
    }

    public JPasswordField getJPSenha() {
        return JPSenha;
    }

    public void setJPSenha(JPasswordField JPSenha) {
        this.JPSenha = JPSenha;
    }

    public JTextField getJTlogin() {
        return JTlogin;
    }

    public void setJTlogin(JTextField JTlogin) {
        this.JTlogin = JTlogin;
    }
    
}
